In [7]:
import pandas as pd
pd.set_option('display.max_rows', 5)
print("Setup complete.")

Setup complete.

In [9]:
fruits = pd.DataFrame({'Apple': [30], 'Bananas': [21]})
fruits

   Apple  Bananas
0     30       21

In [10]:
fruits_sales = pd.DataFrame({
    "Apples": [35, 41],
    "Bananas": [21, 34]
}, index=["2017 Sales", "2018 Sales"])
fruits_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [13]:
# crate a variagle ingredients with a series
ingredients = pd.Series(["4 cups", "1 cup", "2 large", "1 can"],
index=["Flour", "Milk", "Eggs", "Spam"],
name="Dinner")
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: str

In [ ]:
# reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv", index_col=0)

In [15]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [17]:
animals.to_csv("../../outputs/cows_and_goats.csv")

In [19]:
customers = pd.read_csv("../../data/customers.csv", index_col=0)

customers.head()

               name   age region membership
customer_id
C001          佐藤 花子  58.0    名古屋       シルバー
C002          鈴木 一郎  48.0     札幌      レギュラー
C003          高橋 美咲  34.0     大阪      レギュラー
C004          田中 健太   NaN     福岡      レギュラー
C005         伊藤 さくら  27.0     大阪      レギュラー

In [20]:
orders = pd.read_csv("../../data/orders.csv", index_col=0)
orders.head()

,order_date,customer_id,product,category,unit_price,quantity,payment_method
order_id,,,,,,,
1001,2026-04-01,C007,ビジネス書,書籍,1600,3.0,銀行振込
1002,2026-04-02,C002,コーヒー豆,食品,1800,1.0,電子マネー
1003,2026-04-07,C012,マウス,家電,2500,3.0,電子マネー
1004,2026-04-09,C001,ビジネス書,書籍,1600,1.0,電子マネー
1005,2026-04-09,C014,マウス,家電,2500,3.0,クレジットカード

In [25]:
remean_age = customers.age - customers.age.mean()

In [26]:
def stars(row):
    if row.age >= 50:
        return 3
    elif row.age >= 30:
        return 2
    else:
        return 1

star_ratings = customers.apply(stars, axis="columns")

In [ ]:
orders.groupby("category").category.count()
orders.groupby("category").unit_price.min()

category
家電    20
書籍    17
食品    23
Name: category, dtype: int64

In [34]:
orders.groupby("category").unit_price.min()

category
家電    2500
書籍     880
食品     650
Name: unit_price, dtype: int64

In [40]:
orders.groupby("product").apply(lambda df: df.payment_method.iloc[0])

product
キーボード    クレジットカード
コーヒー豆       電子マネー
           ...
技術書      クレジットカード
紅茶       クレジットカード
Length: 9, dtype: str

In [45]:
orders.groupby(["customer_id", "product"]).apply(
    lambda df: df.loc[df.unit_price.idxmax()]
)

                     order_date category  unit_price  quantity payment_method
customer_id product
C001        チョコレート   2026-08-04       食品         650       1.0             現金
            ビジネス書    2026-04-09       書籍        1600       1.0          電子マネー
...                         ...      ...         ...       ...            ...
C014        紅茶       2026-04-21       食品        1200       2.0       クレジットカード
C015        コーヒー豆    2026-07-12       食品        1800       1.0          電子マネー

[45 rows x 5 columns]

In [48]:
orders["total_price"] = orders["quantity"] * orders["unit_price"]

In [49]:
orders

,order_date,customer_id,product,category,unit_price,quantity,payment_method,total_price
order_id,,,,,,,,
1001,2026-04-01,C007,ビジネス書,書籍,1600,3.0,銀行振込,4800.0
1002,2026-04-02,C002,コーヒー豆,食品,1800,1.0,電子マネー,1800.0
...,...,...,...,...,...,...,...,...
1059,2026-09-20,C014,マウス,家電,2500,2.0,銀行振込,5000.0
1060,2026-09-28,C002,コーヒー豆,食品,1800,1.0,電子マネー,1800.0

In [50]:
orders.groupby(["customer_id"]).total_price.agg(["min", "max", "mean"])

                min      max    mean
customer_id
C001          650.0  12500.0  4287.5
C002         1800.0   7500.0  4140.0
...             ...      ...     ...
C014         2400.0   7500.0  4760.0
C015         1800.0   1800.0  1800.0

[14 rows x 3 columns]

In [52]:
orders.sort_values(by="total_price", ascending=False).head(10)

,order_date,customer_id,product,category,unit_price,quantity,payment_method,total_price
order_id,,,,,,,,
1036,2026-07-13,C012,ノートPC,家電,98000,2.0,クレジットカード,196000.0
1055,2026-09-14,C009,ノートPC,家電,98000,1.0,クレジットカード,98000.0
...,...,...,...,...,...,...,...,...
1050,2026-08-15,C012,キーボード,家電,6800,2.0,電子マネー,13600.0
1031,2026-07-05,C013,キーボード,家電,6800,2.0,クレジットカード,13600.0

In [53]:
orders.sort_index().head(10)

,order_date,customer_id,product,category,unit_price,quantity,payment_method,total_price
order_id,,,,,,,,
1001,2026-04-01,C007,ビジネス書,書籍,1600,3.0,銀行振込,4800.0
1002,2026-04-02,C002,コーヒー豆,食品,1800,1.0,電子マネー,1800.0
...,...,...,...,...,...,...,...,...
1009,2026-04-20,C008,コーヒー豆,食品,1800,5.0,クレジットカード,9000.0
1010,2026-04-21,C009,ビジネス書,書籍,1600,3.0,NaN,4800.0